FileVersion = 1

[Project]
Name = "BeefSFMLSystem"
TargetType = "BeefLib"
StartupObject = "Program"
DefaultNamespace = "SFML.System"

[Configs.Release.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-system-2.dll\")"]

[Configs.Release.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-system-2.dll\")"]

[Configs.Debug.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-system-d-2.dll\")"]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-system-2.dll\")"]
