FileVersion = 1
Dependencies = {corlib = "*", BeefSFMLSystem = "*"}

[Project]
Name = "BeefSFMLWindow"
TargetType = "BeefLib"
StartupObject = "Program"
DefaultNamespace = "SFML.Window"

[Configs.Debug.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-window-d-2.dll\")"]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-window-d-2.dll\")"]

[Configs.Release.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-window-2.dll\")"]

[Configs.Release.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-window-2.dll\")"]
