FileVersion = 1
Dependencies = {corlib = "*", BeefSFMLWindow = "*", BeefSFMLSystem = "*"}

[Project]
Name = "BeefSFMLGraphics"
TargetType = "BeefLib"
StartupObject = "Program"
DefaultNamespace = "SFML.Graphics"

[Configs.Debug.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-graphics-d-2.dll\")"]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-graphics-2.dll\")"]

[Configs.Release.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-graphics-2.dll\")"]

[Configs.Release.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-graphics-2.dll\")"]
