FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "BeefSFMLNetwork"
TargetType = "BeefLib"
StartupObject = "Program"
DefaultNamespace = "SFML.Network"

[Configs.Debug.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-network-d-2.dll\")"]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-network-d-2.dll\")"]

[Configs.Release.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-network-2.dll\")"]

[Configs.Release.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/csfml-network-2.dll\")"]
